data:
  raw_path: data/raw/hotel_bookings.csv
  cleaned_filename: cleaned_hotel_bookings.csv

model:
  random_state: 42
  test_size: 0.25
  random_seed: 40

mlflow:
  experiment_name: hotel_booking_pipeline
